tasktracker/urls.py
from django.contrib import admin
from django.urls import path,include
from tasktrackerapp import views as v


urlpatterns = [
    path('', v.home),
    path('admin/', admin.site.urls),
    path('tasktracker',include(('tasktrackerapp.urls','tasktracker'),namespace='TaskTracker')),
]

tasktrackerapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',v.Registration.as_view(),name='register'),
    path('logout',v.logout_view,name='logout'),
    path('addproject',v.addproj,name='project'),
    #path('addproject',v.Project.as_view(),name='project'),
    path('dashboard',v.dashboard,name='dashboard'),
    #path('addtask',v.Tasks.as_view(),name='task'),
    path('taskList',v.TaskList.as_view(),name='tasklist'),
    #path('taskList',v.TaskList,name='tasklist'),
    path('addtask',v.addtask,name='task')


]

tasktrackerapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    department=models.CharField(max_length=15)
    designation=models.CharField(max_length=15)
    
class Project(models.Model):
    proj_name=models.CharField(max_length=20)
    description=models.CharField(max_length=50)
    deadline=models.DateField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.proj_name



class Tasks(models.Model):
    task_name=models.CharField(max_length=20)
    project=models.ForeignKey(Project,on_delete=models.CASCADE)
    start_time=models.TimeField()
    end_time=models.TimeField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.task_name

   
        
    

tasktrackerapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User,Project,Tasks
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import NumberInput



class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password1','password2','department','designation']

class ProjectForm(forms.ModelForm):
    deadline = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    class Meta:
        model=Project
        fields=['proj_name','description','deadline']

    

class TasksForm(forms.ModelForm):
    start_time=forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    end_time=forms.TimeField(widget=forms.TimeInput(format='%H:%M'))

    class Meta:
        model=Tasks
        fields=['task_name','start_time','end_time']

tasktrackerapp/views.py
from django.shortcuts import render,HttpResponse,redirect,HttpResponsePermanentRedirect
from .forms import RegistrationForm,ProjectForm,TasksForm
from .models import Project,Tasks,User
from django.views import View
from django.contrib.auth import login,logout,authenticate
from django.views.generic import TemplateView,FormView,CreateView,ListView, DeleteView, UpdateView

# Create your views here.
def home(request):

            if request.method=='POST':
                username=request.POST.get('username')
                password=request.POST.get('password')
                user=authenticate(request,username=username,password=password)
                if user is not None:
                    request.session['uid']=user.id
                    login(request,user)
                    return dashboard(request)
                else:
                    msg='Wrong Credentials'
                    return HttpResponse('Wrong Credentials. Please try again')
            else:
                return render(request,'login_form.html')

            


class Registration(CreateView):
    form_class=RegistrationForm
    template_name='registration_form.html'
    success_url='/'


def logout_view(request):
    logout(request)
    return redirect('/')


def dashboard(request):
    return render(request,'dashboard.html')

class Project(CreateView):
    form_class=ProjectForm
    template_name='forms.html'
    success_url='tasktrackerdashboard'



from tasktrackerapp import models
def addproj(request):
    
            if request.method=='POST':
                uid=request.session.get('uid')
                u=User.objects.get(id=uid)
                proj=request.POST.get('proj_name')
                desc=request.POST.get('description')
                dl=request.POST.get('deadline')
                new_user = models.Project.objects.create(proj_name=proj,description=desc,deadline=dl,user=u)
                new_user.save()
                   
                return dashboard(request)
            else:
                f=ProjectForm
                return render (request,'forms.html',{'form':f})
        

def addtask(request):
    
            if request.method=='POST':
                id=request.session.get('uid')
                uid=User.objects.get(id=id)
                task=request.POST.get('task_name')
                proj=request.POST.get('project')
                
                proj_id=models.Project.objects.get(id=proj)
                s_time=request.POST.get('start_time')
                e_time=request.POST.get('end_time')
                new_task = Tasks.objects.create(task_name=task, project=proj_id, start_time=s_time,end_time=e_time,user=uid)
                new_task.save()
                return dashboard(request)
            else:
                
                uid=request.session.get('uid')
                u=User.objects.get(id=uid)
                proj=models.Project.objects.filter(user=u)
                print(proj)
                
                
                
                f=TasksForm
                d={'proj':proj,'form':f}
                return render(request,'tasks.html',d)
               


    
from tasktrackerapp import models
class TaskList(ListView):
    model=models.Tasks
    template_name='list.html'

    def get_queryset(self):
        test_filter = self.request.session.get('uid')
        if test_filter:
            object_list=models.Tasks.objects.filter(user=test_filter)
            return object_list
        else:
            return Tasks.objects.all()

            

    

tasktrackerapp/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">



<script>
  $(document).ready(function () {
      $('.dropdown-toggle').dropdown();
  });
</script>

{%load static%}
  <!-- Custom CSS -->
<link href="{%static 'css/style.css'%}" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body style="margin-left: 10px;">
<h1>Dashboard</h1>
<br><br>
<button class="btn btn-primary"><h3><a href="{%url 'TaskTracker:project'%} " style="text-decoration: none; color: white;">Add Project</a></h3></button><br><br>
<button class="btn btn-primary"><h3><a href="{%url 'TaskTracker:task'%} " style="text-decoration: none; color: white;">Add Task</a></h3></button><br><br>

<button class="btn btn-primary"><h3><a href="{%url 'TaskTracker:tasklist'%} " style="text-decoration: none; color: white;">Task List</a></h3></button>




   
                
            

    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>

</body>
</html>

tasktrackerapp/templates/forms.html
<form method="POST">
    {%csrf_token%}
    <table>
        
        <tr>
            {{form.as_table}}
            
            

        </tr>
    
            
        
    </table>
    <input type="submit">
</form>

tasktrackerapp/templates/index.html
<a href="{%url 'TaskTracker:reg'%} ">Register</a>
<a href="{%url 'TaskTracker:login'%} ">Login</a>


<a href="{%url 'TaskTracker:project'%} ">test</a>



<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">



<script>
  $(document).ready(function () {
      $('.dropdown-toggle').dropdown();
  });
</script>

{%load static%}
  <!-- Custom CSS -->
<link href="{%static 'css/style.css'%}" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>
  <div class="container" style="height: 100vh; width: 100%;">
    <form>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

  </div>
  

  

    
      
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>

</body>
</html>

tasktrackerapp/templates/list.html
<table border="1">
    
    <tr>
        <th>Task Name</th>
        <th>project</th>
        <th>Start Time</th>
        <th>End Time</th>



    </tr>
    {% for i in object_list%}
    <tr>
        <td>{{i.task_name}}</td>
        <td>{{i.project}}</td>
        <td>{{i.start_time}}</td>
        <td>{{i.end_time}}</td>
       



    </tr>
    {% endfor %}
</table><br>
<a href="{%url 'TaskTracker:logout'%} ">Log Out</a>

tasktrackerapp/templates/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">



<script>
  $(document).ready(function () {
      $('.dropdown-toggle').dropdown();
  });
</script>

{%load static%}
  <!-- Custom CSS -->
<link href="{%static 'css/style.css'%}" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>
    
    <div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center " style="margin-top: 10%;">
        <div class="col-10 col-md-8 col-lg-6">
            <!-- Form -->
           
            <form class="form-example" action="" method="POST">
                {% csrf_token %}
                <h1 style="text-align: center;">Login Form</h1>
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" class="form-control username" id="username" placeholder="Username..." name="username">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control password" id="password" placeholder="Password..." name="password">
                </div>
                <button type="submit" class="btn btn-primary btn-customized">Login</button>
                
            </form>
            
            <h3>New User? <a href="tasktrackerregister">Register here</a></h3>
            <!-- Form end -->
        </div>
    </div>
    
</div>

    
  

    
      
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>

</body>
</html>

tasktrackerapp/templates/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">



<script>
  $(document).ready(function () {
      $('.dropdown-toggle').dropdown();
  });
</script>

{%load static%}
  <!-- Custom CSS -->
<link href="{%static 'css/style.css'%}" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>
    <div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center " style="margin-top: 0%;">
        <div class="col-10 col-md-8 col-lg-6">
            <!-- Form -->
            <form class="form-example" action="" method="post">
                {%csrf_token%}
                {% load crispy_forms_tags %}
                
                <h1 style="text-align: center;">Registration Form</h1>
                <div class="form-group">
                    {{ form|crispy }}
                </div>
               
                <input type="submit" value="Submit" class="btn btn-primary">
           
            </form>
            
            &nbsp;
            <h6>Already Registered? <a href='/'>Log In here</a></h6>
            <!-- Form end -->
        </div>

    </div>
</div>

tasktrackerapp/templates/tasks.html
<form method="POST">
    {%csrf_token%}
<table border="1">
    <tr>
        <td>Task Name: <input type="text" name='task_name'></td>
    </tr>
    
    <tr>
        
        <td>Project:
            <select name="project">
            {%for i in proj%}
              <option value={{i.id}}>{{i.proj_name}}</option>
            {%endfor%}
              
            </select>
        </td>
        
    </tr>

    <tr>
        <td>Start Time: <input type="time" name="start_time"></td>
    </tr>

    <tr>
        <td>End Time: <input type="time" name="end_time"></td>
    </tr>
    
</table>
    <tr>
        <input type="submit">
    </tr>
</form>

tasktrackerapp/templates/test.html
{%if u%}
{{u}}
{{%endif%}}